# generated by datamodel-codegen:
#   filename:  oas.yaml
#   timestamp: 2021-09-27T14:42:45+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, conint


class Size(Enum):
    small = 'small'
    medium = 'medium'
    big = 'big'


class OrderItemSchema(BaseModel):
    product: str
    size: Size
    quantity: Optional[conint(ge=1)] = 1


class CreateOrderSchema(BaseModel):
    order: List[OrderItemSchema] = Field(..., min_items=1)


class Status(Enum):
    created = 'created'
    paid = 'paid'
    progress = 'progress'
    cancelled = 'cancelled'
    dispatched = 'dispatched'
    delivered = 'delivered'


class GetOrderSchema(CreateOrderSchema):
    id: UUID
    created: datetime
    status: Status
