# generated by datamodel-codegen:
#   filename:  oas.yaml
#   timestamp: 2020-11-07T12:25:59+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, conint


class Size(Enum):
    small = 'small'
    medium = 'medium'
    big = 'big'


class OrderItemSchema(BaseModel):
    product: str
    size: Size
    quantity: Optional[conint(ge=1)] = 1


class CreateOrderSchema(BaseModel):
    order: List[OrderItemSchema]


class Status(Enum):
    created = 'created'
    paid = 'paid'
    progress = 'progress'
    cancelled = 'cancelled'
    dispatched = 'dispatched'
    delivered = 'delivered'


class GetOrderSchema(BaseModel):
    id: UUID
    created: int = Field(..., description='Date in the form of UNIX timestmap')
    status: Status
